-- Insertar 100 bibliotecas
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Central', 'Calle 123');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Norte', 'Carrera 45');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Sur', 'Avenida 89');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Este', 'Calle 50');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Oeste', 'Carrera 10');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Infantil', 'Calle 14');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Juvenil', 'Avenida 25');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Universitaria', 'Calle 7');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Popular', 'Carrera 18');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca del Parque', 'Avenida 3');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Martín', 'Calle 101');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Pedro', 'Carrera 22');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca La Esperanza', 'Calle 45');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Porvenir', 'Carrera 77');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Villa Nueva', 'Avenida 60');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Prado', 'Calle 32');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Bella Vista', 'Carrera 48');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Las Flores', 'Avenida 92');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Santa Ana', 'Calle 15');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Santa Rosa', 'Carrera 13');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San José', 'Avenida 41');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Juan', 'Calle 85');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Pablo', 'Carrera 62');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Lucas', 'Avenida 11');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Carmen', 'Calle 23');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca San Rafael', 'Carrera 55');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Las Colinas', 'Avenida 90');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Los Olivos', 'Calle 76');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Los Pinos', 'Carrera 40');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Bosque', 'Avenida 17');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Lago', 'Calle 99');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Río', 'Carrera 29');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Mar', 'Avenida 28');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca El Sol', 'Calle 65');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca La Luna', 'Carrera 31');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Las Estrellas', 'Avenida 82');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Aurora', 'Calle 58');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Horizonte', 'Carrera 50');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Amanecer', 'Avenida 71');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Atardecer', 'Calle 37');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Ocaso', 'Carrera 16');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Trébol', 'Avenida 94');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Magnolia', 'Calle 46');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Jacarandá', 'Carrera 6');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Laurel', 'Avenida 5');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Cedro', 'Calle 27');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Roble', 'Carrera 36');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Pino', 'Avenida 21');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Encino', 'Calle 54');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Sauce', 'Carrera 24');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Algarrobo', 'Avenida 44');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Acacia', 'Calle 12');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Guayacán', 'Carrera 19');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Ceiba', 'Avenida 14');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Bambú', 'Calle 70');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Loto', 'Carrera 64');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Orquídea', 'Avenida 96');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Tulipán', 'Calle 61');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Rosa', 'Carrera 79');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Girasol', 'Avenida 2');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Violeta', 'Calle 84');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Lirio', 'Carrera 59');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Margarita', 'Avenida 19');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Clavel', 'Calle 8');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Azucena', 'Carrera 5');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Jazmín', 'Avenida 35');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Gardenia', 'Calle 10');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Camelia', 'Carrera 9');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Peonía', 'Avenida 4');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Crisantemo', 'Calle 17');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Dalia', 'Carrera 26');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Hortensia', 'Avenida 12');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Verbena', 'Calle 42');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Lavanda', 'Carrera 33');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Romero', 'Avenida 30');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Tomillo', 'Calle 75');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Salvia', 'Carrera 27');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Menta', 'Avenida 15');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Albahaca', 'Calle 39');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Cilantro', 'Carrera 68');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Perejil', 'Avenida 16');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Orégano', 'Calle 88');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Estragón', 'Carrera 80');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Mejorana', 'Avenida 13');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Hierbabuena', 'Calle 93');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Anís', 'Carrera 34');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Canela', 'Avenida 1');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Pimienta', 'Calle 100');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Nuez Moscada', 'Carrera 46');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Cúrcuma', 'Avenida 57');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Jengibre', 'Calle 6');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Cardamomo', 'Carrera 81');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Comino', 'Avenida 18');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Sésamo', 'Calle 26');
INSERT INTO tb_biblioteca (name, address) VALUES ('Biblioteca Amapola', 'Carrera 43');


-- Insertar 100 autores
INSERT INTO tb_autor (name) VALUES ('Gabriel García Márquez');
INSERT INTO tb_autor (name) VALUES ('Jorge Luis Borges');
INSERT INTO tb_autor (name) VALUES ('Isabel Allende');
INSERT INTO tb_autor (name) VALUES ('Mario Vargas Llosa');
INSERT INTO tb_autor (name) VALUES ('Julio Cortázar');
INSERT INTO tb_autor (name) VALUES ('Laura Esquivel');
INSERT INTO tb_autor (name) VALUES ('Carlos Ruiz Zafón');
INSERT INTO tb_autor (name) VALUES ('Pablo Neruda');
INSERT INTO tb_autor (name) VALUES ('Miguel de Cervantes');
INSERT INTO tb_autor (name) VALUES ('Federico García Lorca');
INSERT INTO tb_autor (name) VALUES ('Ernest Hemingway');
INSERT INTO tb_autor (name) VALUES ('Mark Twain');
INSERT INTO tb_autor (name) VALUES ('Jane Austen');
INSERT INTO tb_autor (name) VALUES ('Charles Dickens');
INSERT INTO tb_autor (name) VALUES ('Leo Tolstoy');
INSERT INTO tb_autor (name) VALUES ('Fyodor Dostoevsky');
INSERT INTO tb_autor (name) VALUES ('Virginia Woolf');
INSERT INTO tb_autor (name) VALUES ('George Orwell');
INSERT INTO tb_autor (name) VALUES ('Aldous Huxley');
INSERT INTO tb_autor (name) VALUES ('J.K. Rowling');
INSERT INTO tb_autor (name) VALUES ('J.R.R. Tolkien');
INSERT INTO tb_autor (name) VALUES ('C.S. Lewis');
INSERT INTO tb_autor (name) VALUES ('Haruki Murakami');
INSERT INTO tb_autor (name) VALUES ('Kazuo Ishiguro');
INSERT INTO tb_autor (name) VALUES ('Chimamanda Ngozi Adichie');
INSERT INTO tb_autor (name) VALUES ('Toni Morrison');
INSERT INTO tb_autor (name) VALUES ('Zadie Smith');
INSERT INTO tb_autor (name) VALUES ('Salman Rushdie');
INSERT INTO tb_autor (name) VALUES ('Arundhati Roy');
INSERT INTO tb_autor (name) VALUES ('Margaret Atwood');
INSERT INTO tb_autor (name) VALUES ('John Steinbeck');
INSERT INTO tb_autor (name) VALUES ('Edgar Allan Poe');
INSERT INTO tb_autor (name) VALUES ('H.P. Lovecraft');
INSERT INTO tb_autor (name) VALUES ('Stephen King');
INSERT INTO tb_autor (name) VALUES ('Neil Gaiman');
INSERT INTO tb_autor (name) VALUES ('Terry Pratchett');
INSERT INTO tb_autor (name) VALUES ('Agatha Christie');
INSERT INTO tb_autor (name) VALUES ('Arthur Conan Doyle');
INSERT INTO tb_autor (name) VALUES ('Alexandre Dumas');
INSERT INTO tb_autor (name) VALUES ('Victor Hugo');
INSERT INTO tb_autor (name) VALUES ('Molière');
INSERT INTO tb_autor (name) VALUES ('Albert Camus');
INSERT INTO tb_autor (name) VALUES ('Jean-Paul Sartre');
INSERT INTO tb_autor (name) VALUES ('Franz Kafka');
INSERT INTO tb_autor (name) VALUES ('Hermann Hesse');
INSERT INTO tb_autor (name) VALUES ('Thomas Mann');
INSERT INTO tb_autor (name) VALUES ('Umberto Eco');
INSERT INTO tb_autor (name) VALUES ('Italo Calvino');
INSERT INTO tb_autor (name) VALUES ('Primo Levi');
INSERT INTO tb_autor (name) VALUES ('José Saramago');
INSERT INTO tb_autor (name) VALUES ('Fernando Pessoa');
INSERT INTO tb_autor (name) VALUES ('Rubén Darío');
INSERT INTO tb_autor (name) VALUES ('Octavio Paz');
INSERT INTO tb_autor (name) VALUES ('Alfonsina Storni');
INSERT INTO tb_autor (name) VALUES ('Claribel Alegría');
INSERT INTO tb_autor (name) VALUES ('Juan Rulfo');
INSERT INTO tb_autor (name) VALUES ('Elena Poniatowska');
INSERT INTO tb_autor (name) VALUES ('Rosa Montero');
INSERT INTO tb_autor (name) VALUES ('Camilo José Cela');
INSERT INTO tb_autor (name) VALUES ('Ana María Matute');
INSERT INTO tb_autor (name) VALUES ('Luis Sepúlveda');
INSERT INTO tb_autor (name) VALUES ('Eduardo Galeano');
INSERT INTO tb_autor (name) VALUES ('Benedetti Mario');
INSERT INTO tb_autor (name) VALUES ('Rafael Alberti');
INSERT INTO tb_autor (name) VALUES ('Antonio Machado');
INSERT INTO tb_autor (name) VALUES ('Javier Marías');
INSERT INTO tb_autor (name) VALUES ('Enrique Vila-Matas');
INSERT INTO tb_autor (name) VALUES ('Santiago Posteguillo');
INSERT INTO tb_autor (name) VALUES ('Ken Follett');
INSERT INTO tb_autor (name) VALUES ('Dan Brown');
INSERT INTO tb_autor (name) VALUES ('Paulo Coelho');
INSERT INTO tb_autor (name) VALUES ('E.L. James');
INSERT INTO tb_autor (name) VALUES ('Suzanne Collins');
INSERT INTO tb_autor (name) VALUES ('Veronica Roth');
INSERT INTO tb_autor (name) VALUES ('George R.R. Martin');
INSERT INTO tb_autor (name) VALUES ('Rick Riordan');
INSERT INTO tb_autor (name) VALUES ('John Green');
INSERT INTO tb_autor (name) VALUES ('Nicholas Sparks');
INSERT INTO tb_autor (name) VALUES ('Colleen Hoover');
INSERT INTO tb_autor (name) VALUES ('Lisa See');
INSERT INTO tb_autor (name) VALUES ('Amy Tan');
INSERT INTO tb_autor (name) VALUES ('Celeste Ng');
INSERT INTO tb_autor (name) VALUES ('Donna Tartt');
INSERT INTO tb_autor (name) VALUES ('Michael Ende');
INSERT INTO tb_autor (name) VALUES ('Cornelia Funke');
INSERT INTO tb_autor (name) VALUES ('Patrick Rothfuss');
INSERT INTO tb_autor (name) VALUES ('Brandon Sanderson');
INSERT INTO tb_autor (name) VALUES ('Robin Hobb');
INSERT INTO tb_autor (name) VALUES ('Robert Jordan');
INSERT INTO tb_autor (name) VALUES ('Anne Rice');
INSERT INTO tb_autor (name) VALUES ('Diana Gabaldon');
INSERT INTO tb_autor (name) VALUES ('Khaled Hosseini');
INSERT INTO tb_autor (name) VALUES ('Orhan Pamuk');
INSERT INTO tb_autor (name) VALUES ('Mo Yan');
INSERT INTO tb_autor (name) VALUES ('Gao Xingjian');
INSERT INTO tb_autor (name) VALUES ('Banana Yoshimoto');
INSERT INTO tb_autor (name) VALUES ('Yukio Mishima');
INSERT INTO tb_autor (name) VALUES ('Kenzaburo Oe');
INSERT INTO tb_autor (name) VALUES ('Natsume Soseki');
INSERT INTO tb_autor (name) VALUES ('Ryunosuke Akutagawa');
INSERT INTO tb_autor (name) VALUES ('Sei Shonagon');


-- Insertar 100 libros
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El túnel', '978-1000000001', 11, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Pedro Páramo', '978-1000000002', 12, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La tregua', '978-1000000003', 13, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Los detectives salvajes', '978-1000000004', 14, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Santa Evita', '978-1000000005', 15, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Hombres de maíz', '978-1000000006', 16, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La invención de Morel', '978-1000000007', 17, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Aura', '978-1000000008', 18, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La región más transparente', '978-1000000009', 19, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Conversación en La Catedral', '978-1000000010', 4, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El Aleph', '978-1000000011', 2, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('2666', '978-1000000012', 14, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El obsceno pájaro de la noche', '978-1000000013', 20, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Sobre héroes y tumbas', '978-1000000014', 11, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La muerte de Artemio Cruz', '978-1000000015', 18, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Señor Presidente', '978-1000000016', 16, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Historia de cronopios y de famas', '978-1000000017', 5, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Un mundo para Julius', '978-1000000018', 21, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Primera memoria', '978-1000000019', 22, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Cuentos completos', '978-1000000020', 2, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Las fuerzas extrañas', '978-1000000021', 23, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El reino de este mundo', '978-1000000022', 24, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Bestiario', '978-1000000023', 5, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Travesuras de la niña mala', '978-1000000024', 4, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Los pasos perdidos', '978-1000000025', 25, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Inés del alma mía', '978-1000000026', 3, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Noticias del Imperio', '978-1000000027', 26, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El laberinto de la soledad', '978-1000000028', 27, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La guerra del fin del mundo', '978-1000000029', 4, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La mujer habitada', '978-1000000030', 28, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Ensayo sobre la ceguera', '978-1000000031', 29, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Santo oficio de la memoria', '978-1000000032', 30, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El astillero', '978-1000000033', 31, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Respiración artificial', '978-1000000034', 32, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La carta esférica', '978-1000000035', 33, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Los mares del sur', '978-1000000036', 34, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Tiempo de silencio', '978-1000000037', 35, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Plata quemada', '978-1000000038', 36, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Corazón tan blanco', '978-1000000039', 37, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Soldados de Salamina', '978-1000000040', 38, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Niebla', '978-1000000041', 39, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El árbol de la ciencia', '978-1000000042', 40, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La familia de Pascual Duarte', '978-1000000043', 41, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Nada', '978-1000000044', 42, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Fortunata y Jacinta', '978-1000000045', 43, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Los santos inocentes', '978-1000000046', 44, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El hereje', '978-1000000047', 45, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La colmena', '978-1000000048', 46, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Requiem por un campesino español', '978-1000000049', 47, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La sombra del ciprés es alargada', '978-1000000050', 48, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La piel del tambor', '978-1000000051', 49, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El maestro de esgrima', '978-1000000052', 33, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La tabla de Flandes', '978-1000000053', 33, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El club Dumas', '978-1000000054', 33, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Patria', '978-1000000055', 50, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La catedral del mar', '978-1000000056', 51, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Los renglones torcidos de Dios', '978-1000000057', 52, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Crónica del rey pasmado', '978-1000000058', 53, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El invierno en Lisboa', '978-1000000059', 54, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El lápiz del carpintero', '978-1000000060', 54, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La sonrisa etrusca', '978-1000000061', 55, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La oscura historia de la prima Montse', '978-1000000062', 56, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La casa de los espíritus', '978-1000000063', 3, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Retrato en sepia', '978-1000000064', 3, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Paula', '978-1000000065', 3, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Eva Luna', '978-1000000066', 3, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('De amor y de sombra', '978-1000000067', 3, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Cien años de soledad', '978-1000000068', 1, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El coronel no tiene quien le escriba', '978-1000000069', 1, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Crónica de una muerte anunciada', '978-1000000070', 1, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El amor en los tiempos del cólera', '978-1000000071', 1, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Del amor y otros demonios', '978-1000000072', 1, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Memoria de mis putas tristes', '978-1000000073', 1, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El general en su laberinto', '978-1000000074', 1, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Doña Bárbara', '978-1000000075', 57, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Cantaclaro', '978-1000000076', 57, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('María', '978-1000000077', 58, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La vorágine', '978-1000000078', 59, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El cartero de Neruda', '978-1000000079', 60, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Fulgor y muerte de Joaquín Murieta', '978-1000000080', 61, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Veinte poemas de amor y una canción desesperada', '978-1000000081', 61, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Residencia en la tierra', '978-1000000082', 61, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Canto general', '978-1000000083', 61, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Confieso que he vivido', '978-1000000084', 61, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('La fiesta del Chivo', '978-1000000085', 4, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Tiempos recios', '978-1000000086', 4, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Cinco esquinas', '978-1000000087', 4, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El héroe discreto', '978-1000000088', 4, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Diario de Greg', '978-1000000089', 62, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('El principito', '978-1000000090', 63, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y la piedra filosofal', '978-1000000091', 64, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y la cámara secreta', '978-1000000092', 64, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y el prisionero de Azkaban', '978-1000000093', 64, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y el cáliz de fuego', '978-1000000094', 64, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y la Orden del Fénix', '978-1000000095', 64, 5);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y el misterio del príncipe', '978-1000000096', 64, 1);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Harry Potter y las Reliquias de la Muerte', '978-1000000097', 64, 2);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Juego de tronos', '978-1000000098', 65, 3);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Choque de reyes', '978-1000000099', 65, 4);
INSERT INTO tb_libro (title, isbn, author_id, library_id) VALUES ('Tormenta de espadas', '978-1000000100', 65, 5);



-- Insertar usuarios
INSERT INTO tb_usuario (name, email) VALUES ('juan', 'juan@example.com');
INSERT INTO tb_usuario (name, email) VALUES ('maria', 'maria@example.com');
INSERT INTO tb_usuario (name, email) VALUES ('pedro', 'pedro@example.com');

INSERT INTO tb_reserva (usuario_id, book_id, date_reservation, is_active) VALUES
(1, 1, TIMESTAMP '2025-07-27 10:00:00', false),
(2, 2, TIMESTAMP '2025-07-27 11:00:00', true),
(3, 3, TIMESTAMP '2025-07-27 12:00:00', true),
(1, 4, TIMESTAMP '2025-07-27 13:00:00', true),
(2, 5, TIMESTAMP '2025-07-27 14:00:00', true),
(3, 6, TIMESTAMP '2025-07-27 15:00:00', true),
(1, 7, TIMESTAMP '2025-07-27 16:00:00', true),
(2, 8, TIMESTAMP '2025-07-27 17:00:00', true),
(3, 9, TIMESTAMP '2025-07-27 18:00:00', true),
(1, 10, TIMESTAMP '2025-07-27 19:00:00', true);



