spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: "library_service"
server:
  port: 8083
author:
  service:
    url: http://localhost:8081/api/v1/books
