spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: "author_service"
server:
  port: 8081

